### PR TITLE
fix: typescript definitions for lowestRate functions

### LINKED ISSUE #395: [Bug]: Type definition of `Shipment.lowestRate` function should not be static
### Software Version

6.6.1

### Language Version

v16.15.1

### Operating System

MacOS Ventura 13.3.1 (a)

### What happened?

The Typescript type definition of `Shipment.lowestRate` defines the function as being static: https://github.com/EasyPost/easypost-node/blob/master/types/Shipment/Shipment.d.ts#L285

In reality, the `Shipment.lowestRate` is not a static function: https://github.com/EasyPost/easypost-node/blob/2c07ac2c727dcffe23eef1543b39fe68a2a65afa/src/models/shipment.js#L44

### What was expected?

The expectation would be that the Typescript type definition defines the `Shipment.lowestRate` function as not being static.

### Sample Code

_No response_

### Relevant logs

_No response_

### PR DESCRIPTION
**Pull request by Justintime50**
# Description

It was reported that the Typescript definitions for `lowestRate` are still static when in reality they are the only functions that are no longer static. This PR fixes the definitions and adds the missing ones for Orders/Pickups.

Closes #395

# Testing

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

### CODE REVIEW

File: types/Order/Order.d.ts [hunk 1]
```diff
@@ -123,4 +124,12 @@ export declare class Order implements IOrder {
...
    */
   static getRates(orderId: string): Promise<IRate[]>;
+
+  /**
+   *
+   * @param carriers a list of carriers to filter rates for.
+   * @param services a list of services to filter rates for.
+   * @returns {Promise<Rate>} The lowest {@link Rate}.
+   */
+  lowestRate(carriers?: string[], services?: string[]): IRate;
```
Comment (ralexmatthews) [inline types/Order/Order.d.ts:134]: Issue:
Hmmm... it says it returns a promise of `Rate`, but the type says it just returns `IRate`. Should this be `Promise<IRate>` instead?

**Review by ralexmatthews — CHANGES_REQUESTED** [review]
Niiiice. Just a small fix needed for these

File: types/Order/Order.d.ts (hunk 1 above)
Comment (Justintime50) [reply types/Order/Order.d.ts:134]: Ooo it's not a promise since we're just filtering a list. I'll fix the returns comment instead

**Review by ralexmatthews — APPROVED** [review]
Nice work dude 👏

**Review by nwithan8 — APPROVED** [review]
